### ISSUE TITLE
Crashes related to speech prefs

### ISSUE THREAD

**Issue by hmijail** [nriley/Pester#16]
Even a freshly built Pester crashed for me because of an uncaught exception on launch.
I deleted a 2-year old Pester plist and lockfile in ~/Library/Preferences, but that didn't stop the crashes.
Seeing the mentions of voice-related difficulties in the webpage and in the stack trace, I tried going into the speech preferences and fumbled a bit. And then Pester managed to launch.

I am not sure what I changed to fix things. The only maybe-interesting thing I saw is that VoiceOver Utility showed as default in the Speech section a voice which didn't seem to be really installed (Fiona compact; I did have Fiona installed, but not the compact version). Once I went into the Dictation & Speech prefs and selected another voice, VoiceOver Utility shows that voice.

XCode 7.1beta on Mac OS X 10.10.5

**Comment by nriley** [comment]
Ouch. I really thought I had fixed all of these problems. Could you attach a copy of a crash report? Thanks.

**Comment by hmijail** [comment]
GitHub is not allowing me to attach the crash report even once renamed to .txt. So I created a gist.
https://gist.github.com/hmijail/6664a9ee91fcbfcab88a

**Comment by nriley** [comment]
I had no idea that VoiceOver Utility had its own speech popup menu.  It does seem to be different from the one in System Preferences in that it lists the compact voices separately, rather than as an unchecked "Upgrade to enhanced quality" checkbox.  `SpeechObjects.framework` in `/System/Library/PrivateFrameworks` exposes all this stuff, which means it's unfortunately not available for use by third-party apps.  As is, I'm reverse-engineering the speech file format to make the voice popup menu in Pester look even reasonably decent.  It's infuriating and gets worse every OS X version with the addition of more and more voices.

Your mention of Fiona was quite helpful.  It turns out Scottish is not a country but a variant (`en-scotland`), which shows up as "Scottish Standard English" in the popup menu, and I hadn't tested with any of those voices.

I may have to release yet another build of 1.1b19 with this change, but I need to get b20 out in the next couple days before El Capitan ships, so it should be in a release soon.  I'd ordinarily build you a copy but I think you can probably do that yourself :-)

Thanks again!

**Comment by hmijail** [comment]
So I guess we were lucky that I typed "voice" instead of "speech" in Spotlight - that's how I learnt about VoiceOver Utility and found about the voice mismatch :). 
No build needed, thanks. Good luck with the rest, it really sounds hairy.
